services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: riwi-tv-nest-dev

    ports:
      - "${APP_PORT}:${APP_PORT}"

    volumes:
      - .:/app
      - /app/node_modules

    depends_on:
      - db
    env_file:
      - ./.env
    environment:
      - NODE_ENV=${NODE_ENV}
      - DATABASE_URL=postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
    deploy:
      resources:
        limits:
          cpus: "${DB_CPU_LIMIT}"
          memory: ${DB_MEM_LIMIT}
    networks:
      - backend

  db:
    image: postgres:16-alpine
    container_name: "${DB_CONTAINER_NAME}"
    ports:
     - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: "${DB_CPU_LIMIT}"
          memory: ${DB_MEM_LIMIT}
    networks:
      - backend

volumes:
  pgdata:

networks:
  backend:
    driver: bridge
